---
- name: my ansible
  hosts: webserver
  remote_user: root
  become: true
  tasks:
        - name: intall httpd
          yum:
               name: httpd
               state: latest
        - name: run httpd
          service:
               name: httpd
               state: started
        - name: create content
          copy:
               content: “Congratulation on installing ansible”
               dest: /var/www/html/index.html